## run with 
## synthetic data should be created first
## slm-run --config config.ini -f queries/city-search-faiss.sparql --debug
##
PREFIX wdt: <http://www.wikidata.org/prop/direct/>    # Propriétés directes (ex. wdt:P31 pour "instance de")
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>  
PREFIX ex: <http://example.org/>

SELECT ?label ?score ?source ?chunk WHERE {
    SERVICE <https://query.wikidata.org/sparql> {
        SELECT *  WHERE {
           ?country wdt:P31 wd:Q6256;  # The country (instance of a sovereign state)
           wdt:P30 wd:Q46;    # Located in Europe (Q46)
           wdt:P36 ?capital.  # Has capital
           ?capital rdfs:label ?label.
           FILTER(LANG(?label) = "en")
        } 
    } 
    BIND(CONCAT("I want a cultural event related to cinema that is located in ",STR(?label)) AS ?rag)
    BIND(ex:SLM-SEARCH-FAISS(?rag,?capital,5) AS ?g).
    GRAPH ?g {
        ?s ex:is_aligned_with ?bn .
        ?bn ex:has_chunk ?chunk .
        ?bn ex:has_source ?source .
        ?bn ex:has_score ?score .
    }    
} order by DESC(?score) limit 10