##
## run with:
## slm-run --config config.ini -f queries/comin_llmf.sparql --debug
## slm-run --load data/UbisoftGamesWD.ttl --config config.ini -f queries/comin_llmf.sparql --debug

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ex: <http://example.org/>
        
SELECT ?game
 WHERE {
    ?root dct:title ?game .
    BIND (ex:SLM-LLMGRAPH_OLLA(CONCAT("""In the video game world, give me
    the price for
    the video game entitled : """,STR(?game)),<http://example.org/has_uri>) as ?llm)
} limit 10