PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX ex: <http://example.org/>

SELECT ?film ?uri ?graph WHERE {
    SERVICE <http://dbpedia.org/sparql> {
        SELECT ?film ?abstract ?title {
            ?film dbo:wikiPageWikiLink dbr:Category:English-language_films .
            ?film dbo:abstract ?abstract .
            ?film rdfs:label ?title .
            FILTER (LANG(?abstract) = "en")
            } LIMIT 1 
        } . 
    BIND(ex:SEGRAPH(REPLACE("Shop selling the film entitled 'FILM' ","FILM",STR(?title)),?film) AS ?graph).
    GRAPH ?graph {?film <http://example.org/has_uri> ?uri}    
} LIMIT 10