PREFIX ex: <http://example.org/>
SELECT *  WHERE {
    BIND(ex:SLM-FILE("./data/zenodo.html") AS ?file)
    BIND(ex:SLM-READHTMLFILE(?file,1000) AS ?page) 
    BIND(CONCAT("""
        return as JSON-LD  the schema.org representation of text below. 
        Only respond with valid JSON-LD : """,
        STR(?page)) AS ?prompt) 
    BIND(ex:SLM-LLMGRAPH(?prompt,ex:myentity) AS ?g)
    GRAPH ?g {
        ?uri <http://example.org/has_schema_type> ?o 
    }    
}