# run with
# slm-run --config config.ini -f queries/simple-csv.sparql --debug
PREFIX ex: <http://example.org/>
SELECT * WHERE {
    BIND(ex:SLM-FILE("./data/results.csv") as ?value)
    BIND(ex:SLM-CSV(?value) AS ?g)
    graph ?g {
        ?x <http://example.org/city> ?z .
    }
}
