##
## run with:
## slm-run --load data/publications.rdf --config config.ini -f queries/simple_publi_llm.sparql --debug
## should see hallucinations.

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ex: <http://example.org/>
        
SELECT ?pub ?journal ?llm
 WHERE {
    ?pub dct:isPartOf ?part .
    ?part dc:title ?journal .
    BIND(CONCAT(""" 
    You are an AI assistant that strictly outputs valid JSON and nothing else.
    DO NOT include any text outside of a valid JSON structure.
    DO NOT include explanations or extra text.
    Respond using this JSON format:
    {
     "impact factor": 5.5,
     "ranking Core": "B",
    }
    Now, provide the evaluation for following the journal or conference: .
    """,STR(?journal)) as ?prompt)
    BIND (ex:SLM-LLM(?prompt) as ?llm)
} limit 10 
