##
## Requires OLAMA to be runing.
##

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX ex: <http://example.org/>

SELECT ?university ?uri ?p1 ?o1
WHERE {
    SERVICE <http://dbpedia.org/sparql> {
        SELECT *  WHERE {
            ?university a dbo:University ;
                dbo:country dbr:France ;
                dbo:numberOfStudents ?nbetu .
            OPTIONAL { ?university rdfs:label ?universityLabel . 
            FILTER (lang(?universityLabel) = "fr") }
        } LIMIT 1
    }
    ## require Google Search API
    BIND(ex:SLM-SEARCH(CONCAT("Official web page of the french university : ",
                            STR(?universityLabel)),?university) AS ?segraph).
    GRAPH ?segraph {?university <http://example.org/has_uri> ?uri}    

    BIND(ex:SLM-BS4(?uri) AS ?page)   
    BIND(CONCAT("""generate in JSON-LD a schema.org representation 
            for a type university of the following page: <page>""", 
            ?page,
            "</page> Output only JSON-LD, no extra text",STR(?page)) AS ?prompt)
    BIND(ex:SLM-LLMGRAPH(?prompt,?uri) AS ?g)
    GRAPH ?g {
        ?uri <http://example.org/has_schema_type> ?root . 
        ?root ?p1 ?o1
    }    
}