PREFIX wd:   <http://www.wikidata.org/entity/>
PREFIX wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX schemas: <https://schema.org/>
PREFIX cand: <http://example.org/cand#>
PREFIX ggf:  <http://ggf.org/>
PREFIX prov:   <http://www.w3.org/ns/prov#>

# Demo: 1-hop local schema around an entity (e.g., wd:Q42)
# slm-run --config config.ini -f queries/entitysearch/wikidata-schema-walk-summerize.sparql --debug

SELECT ?summary ?duration ?ggf
WHERE {
  BIND(wd:Q42 AS ?entity)
  BIND(ggf:WIKIDATA-SCHEMA-WALK(?entity, "en", 50) AS ?gWalk)
  BIND(ggf:SUMMARIZE-RDF-TTL(?gWalk, ?entity) AS ?gSummary)
  GRAPH ?gSummary {
     ?x schema:description ?summary .
  }
  GRAPH ?g {
      ?act a prov:Activity ;
           schemas:duration ?duration ;
           prov:wasAssociatedWith ?ggf .
  }
}
